// Code generated by ent, DO NOT EDIT.

package form_response

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the form_response type in the database.
	Label = "form_response"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldTotalScore holds the string denoting the total_score field in the database.
	FieldTotalScore = "total_score"
	// FieldDepressionLevel holds the string denoting the depression_level field in the database.
	FieldDepressionLevel = "depression_level"
	// EdgeHistoryAnswers holds the string denoting the history_answers edge name in mutations.
	EdgeHistoryAnswers = "history_answers"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the form_response in the database.
	Table = "form_responses"
	// HistoryAnswersTable is the table that holds the history_answers relation/edge.
	HistoryAnswersTable = "history_answers"
	// HistoryAnswersInverseTable is the table name for the History_Answer entity.
	// It exists in this package in order to avoid circular dependency with the "history_answer" package.
	HistoryAnswersInverseTable = "history_answers"
	// HistoryAnswersColumn is the table column denoting the history_answers relation/edge.
	HistoryAnswersColumn = "form_response_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "form_responses"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for form_response fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldUserID,
	FieldTotalScore,
	FieldDepressionLevel,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultTotalScore holds the default value on creation for the "total_score" field.
	DefaultTotalScore uint8
	// TotalScoreValidator is a validator for the "total_score" field. It is called by the builders before save.
	TotalScoreValidator func(uint8) error
	// DepressionLevelValidator is a validator for the "depression_level" field. It is called by the builders before save.
	DepressionLevelValidator func(string) error
)

// OrderOption defines the ordering options for the Form_Response queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByTotalScore orders the results by the total_score field.
func ByTotalScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalScore, opts...).ToFunc()
}

// ByDepressionLevel orders the results by the depression_level field.
func ByDepressionLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepressionLevel, opts...).ToFunc()
}

// ByHistoryAnswersCount orders the results by history_answers count.
func ByHistoryAnswersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newHistoryAnswersStep(), opts...)
	}
}

// ByHistoryAnswers orders the results by history_answers terms.
func ByHistoryAnswers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHistoryAnswersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newHistoryAnswersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HistoryAnswersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, HistoryAnswersTable, HistoryAnswersColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
