// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-gin/database/ent/example"
	"go-gin/database/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExampleUpdate is the builder for updating Example entities.
type ExampleUpdate struct {
	config
	hooks    []Hook
	mutation *ExampleMutation
}

// Where appends a list predicates to the ExampleUpdate builder.
func (eu *ExampleUpdate) Where(ps ...predicate.Example) *ExampleUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetUpdatedAt sets the "updated_at" field.
func (eu *ExampleUpdate) SetUpdatedAt(t time.Time) *ExampleUpdate {
	eu.mutation.SetUpdatedAt(t)
	return eu
}

// SetDeletedAt sets the "deleted_at" field.
func (eu *ExampleUpdate) SetDeletedAt(t time.Time) *ExampleUpdate {
	eu.mutation.SetDeletedAt(t)
	return eu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (eu *ExampleUpdate) SetNillableDeletedAt(t *time.Time) *ExampleUpdate {
	if t != nil {
		eu.SetDeletedAt(*t)
	}
	return eu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (eu *ExampleUpdate) ClearDeletedAt() *ExampleUpdate {
	eu.mutation.ClearDeletedAt()
	return eu
}

// SetName sets the "name" field.
func (eu *ExampleUpdate) SetName(s string) *ExampleUpdate {
	eu.mutation.SetName(s)
	return eu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (eu *ExampleUpdate) SetNillableName(s *string) *ExampleUpdate {
	if s != nil {
		eu.SetName(*s)
	}
	return eu
}

// SetUsername sets the "username" field.
func (eu *ExampleUpdate) SetUsername(s string) *ExampleUpdate {
	eu.mutation.SetUsername(s)
	return eu
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (eu *ExampleUpdate) SetNillableUsername(s *string) *ExampleUpdate {
	if s != nil {
		eu.SetUsername(*s)
	}
	return eu
}

// SetEmail sets the "email" field.
func (eu *ExampleUpdate) SetEmail(s string) *ExampleUpdate {
	eu.mutation.SetEmail(s)
	return eu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (eu *ExampleUpdate) SetNillableEmail(s *string) *ExampleUpdate {
	if s != nil {
		eu.SetEmail(*s)
	}
	return eu
}

// ClearEmail clears the value of the "email" field.
func (eu *ExampleUpdate) ClearEmail() *ExampleUpdate {
	eu.mutation.ClearEmail()
	return eu
}

// Mutation returns the ExampleMutation object of the builder.
func (eu *ExampleUpdate) Mutation() *ExampleMutation {
	return eu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *ExampleUpdate) Save(ctx context.Context) (int, error) {
	eu.defaults()
	return withHooks(ctx, eu.sqlSave, eu.mutation, eu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eu *ExampleUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *ExampleUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *ExampleUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (eu *ExampleUpdate) defaults() {
	if _, ok := eu.mutation.UpdatedAt(); !ok {
		v := example.UpdateDefaultUpdatedAt()
		eu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eu *ExampleUpdate) check() error {
	if v, ok := eu.mutation.Name(); ok {
		if err := example.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Example.name": %w`, err)}
		}
	}
	if v, ok := eu.mutation.Username(); ok {
		if err := example.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Example.username": %w`, err)}
		}
	}
	if v, ok := eu.mutation.Email(); ok {
		if err := example.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Example.email": %w`, err)}
		}
	}
	return nil
}

func (eu *ExampleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := eu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(example.Table, example.Columns, sqlgraph.NewFieldSpec(example.FieldID, field.TypeUUID))
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.UpdatedAt(); ok {
		_spec.SetField(example.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := eu.mutation.DeletedAt(); ok {
		_spec.SetField(example.FieldDeletedAt, field.TypeTime, value)
	}
	if eu.mutation.DeletedAtCleared() {
		_spec.ClearField(example.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := eu.mutation.Name(); ok {
		_spec.SetField(example.FieldName, field.TypeString, value)
	}
	if value, ok := eu.mutation.Username(); ok {
		_spec.SetField(example.FieldUsername, field.TypeString, value)
	}
	if value, ok := eu.mutation.Email(); ok {
		_spec.SetField(example.FieldEmail, field.TypeString, value)
	}
	if eu.mutation.EmailCleared() {
		_spec.ClearField(example.FieldEmail, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{example.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eu.mutation.done = true
	return n, nil
}

// ExampleUpdateOne is the builder for updating a single Example entity.
type ExampleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExampleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (euo *ExampleUpdateOne) SetUpdatedAt(t time.Time) *ExampleUpdateOne {
	euo.mutation.SetUpdatedAt(t)
	return euo
}

// SetDeletedAt sets the "deleted_at" field.
func (euo *ExampleUpdateOne) SetDeletedAt(t time.Time) *ExampleUpdateOne {
	euo.mutation.SetDeletedAt(t)
	return euo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (euo *ExampleUpdateOne) SetNillableDeletedAt(t *time.Time) *ExampleUpdateOne {
	if t != nil {
		euo.SetDeletedAt(*t)
	}
	return euo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (euo *ExampleUpdateOne) ClearDeletedAt() *ExampleUpdateOne {
	euo.mutation.ClearDeletedAt()
	return euo
}

// SetName sets the "name" field.
func (euo *ExampleUpdateOne) SetName(s string) *ExampleUpdateOne {
	euo.mutation.SetName(s)
	return euo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (euo *ExampleUpdateOne) SetNillableName(s *string) *ExampleUpdateOne {
	if s != nil {
		euo.SetName(*s)
	}
	return euo
}

// SetUsername sets the "username" field.
func (euo *ExampleUpdateOne) SetUsername(s string) *ExampleUpdateOne {
	euo.mutation.SetUsername(s)
	return euo
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (euo *ExampleUpdateOne) SetNillableUsername(s *string) *ExampleUpdateOne {
	if s != nil {
		euo.SetUsername(*s)
	}
	return euo
}

// SetEmail sets the "email" field.
func (euo *ExampleUpdateOne) SetEmail(s string) *ExampleUpdateOne {
	euo.mutation.SetEmail(s)
	return euo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (euo *ExampleUpdateOne) SetNillableEmail(s *string) *ExampleUpdateOne {
	if s != nil {
		euo.SetEmail(*s)
	}
	return euo
}

// ClearEmail clears the value of the "email" field.
func (euo *ExampleUpdateOne) ClearEmail() *ExampleUpdateOne {
	euo.mutation.ClearEmail()
	return euo
}

// Mutation returns the ExampleMutation object of the builder.
func (euo *ExampleUpdateOne) Mutation() *ExampleMutation {
	return euo.mutation
}

// Where appends a list predicates to the ExampleUpdate builder.
func (euo *ExampleUpdateOne) Where(ps ...predicate.Example) *ExampleUpdateOne {
	euo.mutation.Where(ps...)
	return euo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *ExampleUpdateOne) Select(field string, fields ...string) *ExampleUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Example entity.
func (euo *ExampleUpdateOne) Save(ctx context.Context) (*Example, error) {
	euo.defaults()
	return withHooks(ctx, euo.sqlSave, euo.mutation, euo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (euo *ExampleUpdateOne) SaveX(ctx context.Context) *Example {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *ExampleUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *ExampleUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (euo *ExampleUpdateOne) defaults() {
	if _, ok := euo.mutation.UpdatedAt(); !ok {
		v := example.UpdateDefaultUpdatedAt()
		euo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (euo *ExampleUpdateOne) check() error {
	if v, ok := euo.mutation.Name(); ok {
		if err := example.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Example.name": %w`, err)}
		}
	}
	if v, ok := euo.mutation.Username(); ok {
		if err := example.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Example.username": %w`, err)}
		}
	}
	if v, ok := euo.mutation.Email(); ok {
		if err := example.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Example.email": %w`, err)}
		}
	}
	return nil
}

func (euo *ExampleUpdateOne) sqlSave(ctx context.Context) (_node *Example, err error) {
	if err := euo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(example.Table, example.Columns, sqlgraph.NewFieldSpec(example.FieldID, field.TypeUUID))
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Example.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, example.FieldID)
		for _, f := range fields {
			if !example.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != example.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.UpdatedAt(); ok {
		_spec.SetField(example.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := euo.mutation.DeletedAt(); ok {
		_spec.SetField(example.FieldDeletedAt, field.TypeTime, value)
	}
	if euo.mutation.DeletedAtCleared() {
		_spec.ClearField(example.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := euo.mutation.Name(); ok {
		_spec.SetField(example.FieldName, field.TypeString, value)
	}
	if value, ok := euo.mutation.Username(); ok {
		_spec.SetField(example.FieldUsername, field.TypeString, value)
	}
	if value, ok := euo.mutation.Email(); ok {
		_spec.SetField(example.FieldEmail, field.TypeString, value)
	}
	if euo.mutation.EmailCleared() {
		_spec.ClearField(example.FieldEmail, field.TypeString)
	}
	_node = &Example{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{example.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	euo.mutation.done = true
	return _node, nil
}
