// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-gin/database/ent/form_response"
	"go-gin/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FormResponseDelete is the builder for deleting a Form_Response entity.
type FormResponseDelete struct {
	config
	hooks    []Hook
	mutation *FormResponseMutation
}

// Where appends a list predicates to the FormResponseDelete builder.
func (frd *FormResponseDelete) Where(ps ...predicate.Form_Response) *FormResponseDelete {
	frd.mutation.Where(ps...)
	return frd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (frd *FormResponseDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, frd.sqlExec, frd.mutation, frd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (frd *FormResponseDelete) ExecX(ctx context.Context) int {
	n, err := frd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (frd *FormResponseDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(form_response.Table, sqlgraph.NewFieldSpec(form_response.FieldID, field.TypeInt))
	if ps := frd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, frd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	frd.mutation.done = true
	return affected, err
}

// FormResponseDeleteOne is the builder for deleting a single Form_Response entity.
type FormResponseDeleteOne struct {
	frd *FormResponseDelete
}

// Where appends a list predicates to the FormResponseDelete builder.
func (frdo *FormResponseDeleteOne) Where(ps ...predicate.Form_Response) *FormResponseDeleteOne {
	frdo.frd.mutation.Where(ps...)
	return frdo
}

// Exec executes the deletion query.
func (frdo *FormResponseDeleteOne) Exec(ctx context.Context) error {
	n, err := frdo.frd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{form_response.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (frdo *FormResponseDeleteOne) ExecX(ctx context.Context) {
	if err := frdo.Exec(ctx); err != nil {
		panic(err)
	}
}
