// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"go-gin/database/ent/form_response"
	"go-gin/database/ent/history_answer"
	"go-gin/database/ent/predicate"
	"go-gin/database/ent/user"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FormResponseQuery is the builder for querying Form_Response entities.
type FormResponseQuery struct {
	config
	ctx                *QueryContext
	order              []form_response.OrderOption
	inters             []Interceptor
	predicates         []predicate.Form_Response
	withHistoryAnswers *HistoryAnswerQuery
	withUser           *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FormResponseQuery builder.
func (frq *FormResponseQuery) Where(ps ...predicate.Form_Response) *FormResponseQuery {
	frq.predicates = append(frq.predicates, ps...)
	return frq
}

// Limit the number of records to be returned by this query.
func (frq *FormResponseQuery) Limit(limit int) *FormResponseQuery {
	frq.ctx.Limit = &limit
	return frq
}

// Offset to start from.
func (frq *FormResponseQuery) Offset(offset int) *FormResponseQuery {
	frq.ctx.Offset = &offset
	return frq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (frq *FormResponseQuery) Unique(unique bool) *FormResponseQuery {
	frq.ctx.Unique = &unique
	return frq
}

// Order specifies how the records should be ordered.
func (frq *FormResponseQuery) Order(o ...form_response.OrderOption) *FormResponseQuery {
	frq.order = append(frq.order, o...)
	return frq
}

// QueryHistoryAnswers chains the current query on the "history_answers" edge.
func (frq *FormResponseQuery) QueryHistoryAnswers() *HistoryAnswerQuery {
	query := (&HistoryAnswerClient{config: frq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := frq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := frq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(form_response.Table, form_response.FieldID, selector),
			sqlgraph.To(history_answer.Table, history_answer.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, form_response.HistoryAnswersTable, form_response.HistoryAnswersColumn),
		)
		fromU = sqlgraph.SetNeighbors(frq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (frq *FormResponseQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: frq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := frq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := frq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(form_response.Table, form_response.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, form_response.UserTable, form_response.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(frq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Form_Response entity from the query.
// Returns a *NotFoundError when no Form_Response was found.
func (frq *FormResponseQuery) First(ctx context.Context) (*Form_Response, error) {
	nodes, err := frq.Limit(1).All(setContextOp(ctx, frq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{form_response.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (frq *FormResponseQuery) FirstX(ctx context.Context) *Form_Response {
	node, err := frq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Form_Response ID from the query.
// Returns a *NotFoundError when no Form_Response ID was found.
func (frq *FormResponseQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = frq.Limit(1).IDs(setContextOp(ctx, frq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{form_response.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (frq *FormResponseQuery) FirstIDX(ctx context.Context) int {
	id, err := frq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Form_Response entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Form_Response entity is found.
// Returns a *NotFoundError when no Form_Response entities are found.
func (frq *FormResponseQuery) Only(ctx context.Context) (*Form_Response, error) {
	nodes, err := frq.Limit(2).All(setContextOp(ctx, frq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{form_response.Label}
	default:
		return nil, &NotSingularError{form_response.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (frq *FormResponseQuery) OnlyX(ctx context.Context) *Form_Response {
	node, err := frq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Form_Response ID in the query.
// Returns a *NotSingularError when more than one Form_Response ID is found.
// Returns a *NotFoundError when no entities are found.
func (frq *FormResponseQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = frq.Limit(2).IDs(setContextOp(ctx, frq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{form_response.Label}
	default:
		err = &NotSingularError{form_response.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (frq *FormResponseQuery) OnlyIDX(ctx context.Context) int {
	id, err := frq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Form_Responses.
func (frq *FormResponseQuery) All(ctx context.Context) ([]*Form_Response, error) {
	ctx = setContextOp(ctx, frq.ctx, "All")
	if err := frq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Form_Response, *FormResponseQuery]()
	return withInterceptors[[]*Form_Response](ctx, frq, qr, frq.inters)
}

// AllX is like All, but panics if an error occurs.
func (frq *FormResponseQuery) AllX(ctx context.Context) []*Form_Response {
	nodes, err := frq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Form_Response IDs.
func (frq *FormResponseQuery) IDs(ctx context.Context) (ids []int, err error) {
	if frq.ctx.Unique == nil && frq.path != nil {
		frq.Unique(true)
	}
	ctx = setContextOp(ctx, frq.ctx, "IDs")
	if err = frq.Select(form_response.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (frq *FormResponseQuery) IDsX(ctx context.Context) []int {
	ids, err := frq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (frq *FormResponseQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, frq.ctx, "Count")
	if err := frq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, frq, querierCount[*FormResponseQuery](), frq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (frq *FormResponseQuery) CountX(ctx context.Context) int {
	count, err := frq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (frq *FormResponseQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, frq.ctx, "Exist")
	switch _, err := frq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (frq *FormResponseQuery) ExistX(ctx context.Context) bool {
	exist, err := frq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FormResponseQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (frq *FormResponseQuery) Clone() *FormResponseQuery {
	if frq == nil {
		return nil
	}
	return &FormResponseQuery{
		config:             frq.config,
		ctx:                frq.ctx.Clone(),
		order:              append([]form_response.OrderOption{}, frq.order...),
		inters:             append([]Interceptor{}, frq.inters...),
		predicates:         append([]predicate.Form_Response{}, frq.predicates...),
		withHistoryAnswers: frq.withHistoryAnswers.Clone(),
		withUser:           frq.withUser.Clone(),
		// clone intermediate query.
		sql:  frq.sql.Clone(),
		path: frq.path,
	}
}

// WithHistoryAnswers tells the query-builder to eager-load the nodes that are connected to
// the "history_answers" edge. The optional arguments are used to configure the query builder of the edge.
func (frq *FormResponseQuery) WithHistoryAnswers(opts ...func(*HistoryAnswerQuery)) *FormResponseQuery {
	query := (&HistoryAnswerClient{config: frq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	frq.withHistoryAnswers = query
	return frq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (frq *FormResponseQuery) WithUser(opts ...func(*UserQuery)) *FormResponseQuery {
	query := (&UserClient{config: frq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	frq.withUser = query
	return frq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FormResponse.Query().
//		GroupBy(form_response.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (frq *FormResponseQuery) GroupBy(field string, fields ...string) *FormResponseGroupBy {
	frq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FormResponseGroupBy{build: frq}
	grbuild.flds = &frq.ctx.Fields
	grbuild.label = form_response.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.FormResponse.Query().
//		Select(form_response.FieldCreatedAt).
//		Scan(ctx, &v)
func (frq *FormResponseQuery) Select(fields ...string) *FormResponseSelect {
	frq.ctx.Fields = append(frq.ctx.Fields, fields...)
	sbuild := &FormResponseSelect{FormResponseQuery: frq}
	sbuild.label = form_response.Label
	sbuild.flds, sbuild.scan = &frq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FormResponseSelect configured with the given aggregations.
func (frq *FormResponseQuery) Aggregate(fns ...AggregateFunc) *FormResponseSelect {
	return frq.Select().Aggregate(fns...)
}

func (frq *FormResponseQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range frq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, frq); err != nil {
				return err
			}
		}
	}
	for _, f := range frq.ctx.Fields {
		if !form_response.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if frq.path != nil {
		prev, err := frq.path(ctx)
		if err != nil {
			return err
		}
		frq.sql = prev
	}
	return nil
}

func (frq *FormResponseQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Form_Response, error) {
	var (
		nodes       = []*Form_Response{}
		_spec       = frq.querySpec()
		loadedTypes = [2]bool{
			frq.withHistoryAnswers != nil,
			frq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Form_Response).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Form_Response{config: frq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, frq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := frq.withHistoryAnswers; query != nil {
		if err := frq.loadHistoryAnswers(ctx, query, nodes,
			func(n *Form_Response) { n.Edges.HistoryAnswers = []*History_Answer{} },
			func(n *Form_Response, e *History_Answer) { n.Edges.HistoryAnswers = append(n.Edges.HistoryAnswers, e) }); err != nil {
			return nil, err
		}
	}
	if query := frq.withUser; query != nil {
		if err := frq.loadUser(ctx, query, nodes, nil,
			func(n *Form_Response, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (frq *FormResponseQuery) loadHistoryAnswers(ctx context.Context, query *HistoryAnswerQuery, nodes []*Form_Response, init func(*Form_Response), assign func(*Form_Response, *History_Answer)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Form_Response)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(history_answer.FieldFormResponseID)
	}
	query.Where(predicate.History_Answer(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(form_response.HistoryAnswersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.FormResponseID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "form_response_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (frq *FormResponseQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*Form_Response, init func(*Form_Response), assign func(*Form_Response, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Form_Response)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (frq *FormResponseQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := frq.querySpec()
	_spec.Node.Columns = frq.ctx.Fields
	if len(frq.ctx.Fields) > 0 {
		_spec.Unique = frq.ctx.Unique != nil && *frq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, frq.driver, _spec)
}

func (frq *FormResponseQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(form_response.Table, form_response.Columns, sqlgraph.NewFieldSpec(form_response.FieldID, field.TypeInt))
	_spec.From = frq.sql
	if unique := frq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if frq.path != nil {
		_spec.Unique = true
	}
	if fields := frq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, form_response.FieldID)
		for i := range fields {
			if fields[i] != form_response.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if frq.withUser != nil {
			_spec.Node.AddColumnOnce(form_response.FieldUserID)
		}
	}
	if ps := frq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := frq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := frq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := frq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (frq *FormResponseQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(frq.driver.Dialect())
	t1 := builder.Table(form_response.Table)
	columns := frq.ctx.Fields
	if len(columns) == 0 {
		columns = form_response.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if frq.sql != nil {
		selector = frq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if frq.ctx.Unique != nil && *frq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range frq.predicates {
		p(selector)
	}
	for _, p := range frq.order {
		p(selector)
	}
	if offset := frq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := frq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FormResponseGroupBy is the group-by builder for Form_Response entities.
type FormResponseGroupBy struct {
	selector
	build *FormResponseQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (frgb *FormResponseGroupBy) Aggregate(fns ...AggregateFunc) *FormResponseGroupBy {
	frgb.fns = append(frgb.fns, fns...)
	return frgb
}

// Scan applies the selector query and scans the result into the given value.
func (frgb *FormResponseGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, frgb.build.ctx, "GroupBy")
	if err := frgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FormResponseQuery, *FormResponseGroupBy](ctx, frgb.build, frgb, frgb.build.inters, v)
}

func (frgb *FormResponseGroupBy) sqlScan(ctx context.Context, root *FormResponseQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(frgb.fns))
	for _, fn := range frgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*frgb.flds)+len(frgb.fns))
		for _, f := range *frgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*frgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := frgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FormResponseSelect is the builder for selecting fields of FormResponse entities.
type FormResponseSelect struct {
	*FormResponseQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (frs *FormResponseSelect) Aggregate(fns ...AggregateFunc) *FormResponseSelect {
	frs.fns = append(frs.fns, fns...)
	return frs
}

// Scan applies the selector query and scans the result into the given value.
func (frs *FormResponseSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, frs.ctx, "Select")
	if err := frs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FormResponseQuery, *FormResponseSelect](ctx, frs.FormResponseQuery, frs, frs.inters, v)
}

func (frs *FormResponseSelect) sqlScan(ctx context.Context, root *FormResponseQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(frs.fns))
	for _, fn := range frs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*frs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := frs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
