// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-gin/database/ent/predicate"
	"go-gin/database/ent/questions"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuestionsDelete is the builder for deleting a Questions entity.
type QuestionsDelete struct {
	config
	hooks    []Hook
	mutation *QuestionsMutation
}

// Where appends a list predicates to the QuestionsDelete builder.
func (qd *QuestionsDelete) Where(ps ...predicate.Questions) *QuestionsDelete {
	qd.mutation.Where(ps...)
	return qd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (qd *QuestionsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, qd.sqlExec, qd.mutation, qd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (qd *QuestionsDelete) ExecX(ctx context.Context) int {
	n, err := qd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (qd *QuestionsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(questions.Table, sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt))
	if ps := qd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, qd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	qd.mutation.done = true
	return affected, err
}

// QuestionsDeleteOne is the builder for deleting a single Questions entity.
type QuestionsDeleteOne struct {
	qd *QuestionsDelete
}

// Where appends a list predicates to the QuestionsDelete builder.
func (qdo *QuestionsDeleteOne) Where(ps ...predicate.Questions) *QuestionsDeleteOne {
	qdo.qd.mutation.Where(ps...)
	return qdo
}

// Exec executes the deletion query.
func (qdo *QuestionsDeleteOne) Exec(ctx context.Context) error {
	n, err := qdo.qd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{questions.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (qdo *QuestionsDeleteOne) ExecX(ctx context.Context) {
	if err := qdo.Exec(ctx); err != nil {
		panic(err)
	}
}
