// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category_Questions is the predicate function for category_questions builders.
type Category_Questions func(*sql.Selector)

// Example is the predicate function for example builders.
type Example func(*sql.Selector)

// Form_Response is the predicate function for form_response builders.
type Form_Response func(*sql.Selector)

// History_Answer is the predicate function for history_answer builders.
type History_Answer func(*sql.Selector)

// Questions is the predicate function for questions builders.
type Questions func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
